export {default as HomePage} from "./HomePage"
export {default as About} from "./About"
export {default as Products} from "./Products"
export {default as Turms} from "./Turms"
export {default as Footer} from "./Footer"
export {default as Questions} from "./Questions"
