export {default as HomePage} from "./HomePage"
export {default as RegisterPage} from "./RegisterPage"
export {default as LoginPage} from "./LoginPage"
export {default as About} from "./About"
export {default as Products} from "./Products"
export {default as Questions} from "./Questions"
export {default as Jobs} from "./Jobs"
export {default as Turms} from "./Turms"
export {default as Footer} from "./Footer"

